{% set name = "vedo" %}
{% set version = "2024.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6e1fa7ab20460470cdafc7698997114d970acfb552131aae062eb4412087e02a

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - vtk
    - numpy
    - Deprecated

test:
  requires:
    - python {{ python_min }}
  imports:
    - vedo

about:
  home: https://github.com/marcomusy/vedo/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A python module for scientific visualization, analysis and animation of 3D objects and point clouds based on VTK.
  doc_url: https://github.com/marcomusy/vedo/
  dev_url: https://github.com/marcomusy/vedo/

extra:
  recipe-maintainers:
    - RubendeBruin
    - marcomusy
