{% set name = "vedo" %}
{% set version = "2022.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f9dd3c738f526f91e51714d042abc8a906eb564a2298e121f2ab580130b9509d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - vtk
    - numpy
    - Deprecated

test:
  imports:
    - vedo

about:
  home: https://github.com/marcomusy/vedo/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A python module for scientific visualization, analysis and animation of 3D objects and point clouds based on VTK.
  doc_url: https://github.com/marcomusy/vedo/
  dev_url: https://github.com/marcomusy/vedo/

extra:
  recipe-maintainers:
    - RubendeBruin
    - marcomusy
